### ISSUE TITLE
System hangs if the Kindle has mounted as a disk

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/logcards#4]
From https://github.com/DoESLiverpool/somebody-should/issues/81

From time to time the Kindle in the door of Dinky displays info about charging it rather than the "DoES Liverpool" logo. When it does that, the door lock fails to work.

We should (a) work out how to stop it getting into that state, as it would be better not to display info about charging, etc., and (b) tweak the scripts so that it doesn't interfere with the main operation of the door :-)

**Comment by amcewen** [comment]
Although that fixes the issue on bootup (so a power-cycle fixes it), there have been a couple of times recently (last Friday, and today, for example) when the Kindle has got into the disk state, so it's not a complete fix

**Comment by johnmckerrell** [comment]
Going to close this as the Kindle's not implemented. If it gets put back into place and has this issue, we can reopen it.
