### ISSUE TITLE
Each login leaves at least one zombie ruby process

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/logcards#9]
When investigating https://github.com/DoESLiverpool/somebody-should/issues/871 I noticed there are lots of `[ruby] <defunct>` entries if you run `ps aux`.

It seems to happen whenever someone logs in, and my tag spawns two zombie processes each time I log in.

**Comment by skos-ninja** [comment]
Is this possible to do with the new logging of doorbot entries to Slack that @johnmckerrell did recently?

**Comment by amcewen** [comment]
@skos-ninja that was my first suspicion, but it doesn't look like it.  I think I'll have a fix in a couple of minutes.
